export const enum ErrorCode {
  RECIPE_NOT_FOUND = "RECIPE_NOT_FOUND",
  RECIPE_ALREADY_EXISTS = "RECIPE_ALREADY_EXISTS",
  RECIPE_NAME_CANNOT_BE_EMPTY = "RECIPE_NAME_CANNOT_BE_EMPTY",
  RECIPE_DESCRIPTION_CANNOT_BE_EMPTY = "RECIPE_DESCRIPTION_CANNOT_BE_EMPTY",
  INVALID_PARAMETERS = "INVALID_PARAMETERS",
  INTERNAL_ERROR = "INTERNAL_ERROR",
}
